### ISSUE TITLE
Socks proxy under linux

### ISSUE THREAD

**Issue by alcarinque-istar** [moonlight-stream/moonlight-chrome#480]
I am trying to access a Windows 10 server running nvidia-experience app. 
My client computer is behind a firewall but I can enter the local network through a ssh tunnel. This is my setup:

`| Client PC | -->  | Firewall | --> (internet)  --> | Ssh Server | --> | Windows PC |`

I tried running google-chrome in the client pc with the
` google-chrome-stable --proxy-server="socks5://127.0.0.1:54321" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE 127.0.0.1" `
command line, but when trying to pair moonlight says: Pairing to 192.168.... failed.
The console gives:
```
*   Trying 192.168.......
* Connection timed out after 3000 milliseconds
* Closing connection 0
* getaddrinfo(3) failed for 192.168..local:47984
* Couldn't resolve host '192.168....local'
* Closing connection 0
* getaddrinfo(3) failed for :47984
* Couldn't resolve host ''
* Closing connection 0
*   Trying 192.168....
* Connection timed out after 3000 milliseconds
* Closing connection 0
```
```

I used proxychains to run the old java app and I can pair, but it gives me this error in console:
[proxychains] config file found: /home/alcarinque/.proxychains/hydra/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
Jun 26, 2018 4:43:59 PM com.limelight.LimeLog info
INFO: Reading Preferences
Jun 26, 2018 4:44:15 PM com.limelight.LimeLog info
INFO: Writing Preferences
Jun 26, 2018 4:44:15 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  10.0.0.16:47984  ...  OK
Jun 26, 2018 4:44:18 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  10.0.0.16:47984  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  tmp:21 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  tmp:21 <--socket error or timeout!
Jun 26, 2018 4:44:22 PM com.limelight.LimeLog info
INFO: Starting Sid Meier's Civilization VI
Jun 26, 2018 4:44:22 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  10.0.0.16:47984  ...  OK
Jun 26, 2018 4:44:23 PM com.limelight.LimeLog info
INFO: Server major version: 7
Jun 26, 2018 4:44:23 PM com.limelight.LimeLog info
INFO: Using deprecated app lookup method - Please specify an app ID in your StreamConfiguration instead
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  10.0.0.16:47984  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:54321  ...  10.0.0.16:47984  ...  OK
Jun 26, 2018 4:44:28 PM com.limelight.LimeLog info
INFO: Resumed existing game session
Jun 26, 2018 4:44:28 PM com.limelight.LimeLog info
INFO: Starting RTSP handshake
java.io.IOException: Unable to connect to UDP port 48010
	at com.limelight.nvstream.enet.EnetConnection.connect(EnetConnection.java:34)
	at com.limelight.nvstream.rtsp.RtspConnection.doRtspHandshake(RtspConnection.java:225)
	at com.limelight.nvstream.NvConnection.doRtspHandshake(NvConnection.java:265)
	at com.limelight.nvstream.NvConnection.establishConnection(NvConnection.java:321)
	at com.limelight.nvstream.NvConnection.access$3(NvConnection.java:302)
	at com.limelight.nvstream.NvConnection$1.run(NvConnection.java:374)
	at java.lang.Thread.run(Thread.java:748)

```

I checked the ports from the ssh server using nmap:
```
[alcarinque@Ithaqua ~]$ nmap 192.168... -p 47984,48010  
Starting Nmap 7.70 ( https://nmap.org ) at 2018-06-26 16:48 -03
Nmap scan report for  192.168... 
Host is up (0.00041s latency).

PORT      STATE SERVICE
47984/tcp open  unknown
48010/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 11.21 seconds


```

Is there anything else I could try?

**Comment by Jorys-Paulin** [comment]
@alcarinque-istar I see you don't have all the ports opened in their correct protocols. See here for the full list as well as their protocols: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet

**Comment by Jorys-Paulin** [comment]
@alcarinque-istar I'm no expert know this, but I know that some ports are booth TCP AND UDP

**Comment by steven200796** [comment]
Bump on this!

**Comment by Jorys-Paulin** [comment]
@steven200796 I'm not expert into this; I'll probably need @cgutman's help on that bug

**Comment by cainiaocome** [comment]
try [this](https://github.com/hmgle/graftcp)
